### ISSUE TITLE
Installing this plugin on a vanilla multi container setup (data and web_only) makes discourse spit 503's

### ISSUE THREAD

**Issue by chamunks** [tcreativo/plugin_discourse_statistics#1]
Testing a fresh build with just this plugin of course.

**Comment by territoriocreativo** [comment]
Hi @chamunks, this plugin is no longer necessary to obtain stats from users, since Discourse team merged a pull request to the core code:
https://github.com/discourse/discourse/pull/2936

We'll add a note in the Readme to communicate that this plugin is for dev interest only. As we comment, the feature this plugin was made is already provided in the core software (from 1.2 version and beyond).

**Comment by chamunks** [comment]
Oh awesome cheers!
